server.port: 9999
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
spring.application.name: auth-server
app.auth.host: localhost
spring.main.allow-bean-definition-overriding: true
spring:
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/review
    username: chau
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # or `create-drop` for fresh schema creation during development
    show-sql: true       # Show SQL queries in the console (optional)
    database-platform: org.hibernate.dialect.MySQL8Dialect

resilience4j.circuitbreaker:
  instances:
    product:
      allowHealthIndicatorToFail: false
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      ignoreExceptions:
        - se.chau.microservices.api.exception.InvalidInputException
        - se.chau.microservices.api.exception.NotFoundException
management.tracing.sampling.probability: 1.0

---
spring.config.activate.on-profile: docker
server.port: 80
app.auth.host: auth-server
zipkin:
  baseUrl: http://127.0.0.1:9411
  sender:
    type: web
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/review
    username: chau
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # or `create-drop` for fresh schema creation during development
    show-sql: true       # Show SQL queries in the console (optional)
    database-platform: org.hibernate.dialect.MySQL8Dialect
spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka
---
spring.config.activate.on-profile: prod

logging.level.root: WARN