server.port: 8092
spring:
  cloud:
    compatibility-verifier:
      enabled: false
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:9999

#doeu iubp eyrj zvqa

spring.mail.username: test@gmail.com
spring.mail.properties.mail.smtp.starttls.required: true
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.password: your password
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.transport.protocol: smtp
spring.mail.properties.mail.smtp.starttls.enable: true