version : '1.1'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: review
      MYSQL_USER: chau
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 5s
      timeout: 2s
      retries: 60
    volumes:
      - mysql_data:/var/lib/mysql
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: chau
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 5s
      timeout: 2s
      retries: 60
    volumes:
      - mongo_data:/data/db
  product:
    depends_on:
      - mongodb
    build: Microservices/product
    mem_limit: 512m
    environment:
      -  SPRING_PROFILES_ACTIVE=docker

  product-composite:
    build: Microservices/product_composite
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  review:
    build: Microservices/review
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
  recommendation:
    build: Microservices/recommendation
    depends_on:
      - mongodb
    mem_limit: 512m
    environment:
      -  SPRING_PROFILES_ACTIVE=docker
volumes:
  mongo_data: {}
  mysql_data: {}
