services:
  mysqldbmaster:
    container_name: mysqldbmaster
    image: mysql:latest
    restart: unless-stopped
    expose:
      - 3306
    ports:
      - 3306:3306   
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root
    cap_add:
      - all
    networks:
      - host
    volumes:
      - ./data/master:/var/lib/mysql      
      - ./data/master:/ect/my.cnf
      # - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
  mysqldbslave:
    container_name: mysqldbslave
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_USER=slave
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=root
    cap_add:
      - all
    networks:
      - host
    expose:
      - 3307
    ports:
      - 3307:3307   
    volumes:
      - ./data/slave:/var/lib/mysql      
      - ./data/slave/:/ect/my.cnf
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    #docker.elastic.co/elasticsearch/elasticsearch
    # 8.x
    environment: ['CLI_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
    ports:
      - 9200:9200
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:    
      resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
    ports:
      - 5601:5601
    networks:
      - elastic
    deploy:    
      resources:
          limits:
            cpus: '2.0'
          reservations:
            cpus: '1.0'
  redis:
    image: redislabs/redisinsight:latest
    container_name: cache
    ports:
      - 6379:6379
  nginx:
    container_name: nginx
    image: nginx:1.24.0
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/
      - ./nginx/config.d/:/etc/nginx/conf.d/
      # /etc/nginx/conf.d//
    ports:
      - '9998:80'
      - '9999:81'
networks:
  esnet:
  host:
  elastic:
    driver: bridge
  els:
   name: elastic
   external: false