spring.config.import: "optional:configserver:"
app.eureka: localhost
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
spring:
  application.name: recommendation
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 10000
        maxAttempts: 20
      uri: http://localhost:8888
      username: user
      password: 123
---
spring.config.activate.on-profile: docker

spring.cloud.config.uri: http://config-server:8888