server:
  port: 8761
spring.main.allow-bean-definition-overriding: true
spring:
  cloud:
    compatibility-verifier:
      enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  # from: https://github.com/spring-cloud-samples/eureka/blob/master/src/main/resources/application.yml
  server:
    waitTimeInMsWhenSyncEmpty: 0
    response-cache-update-interval-ms: 5000
    renewal-percent-threshold: 0.85

management.endpoints.web.exposure.include: "*"