server:
  port: 8761

app:
  eureka-username: chau
  eureka-password: 123
#server.ssl:
#  key-store-type: PKCS12
#  key-store: classpath:keystore/edge.p12
#  key-store-password: 013234656798ntaA@
#  key-alias: localhost
eureka:
  instance:
    hostname: localhost
  client:
    leaseRenewalIntervalInSeconds: 30  # Default is 30 seconds
    leaseExpirationDurationInSeconds: 90
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  # from: https://github.com/spring-cloud-samples/eureka/blob/master/src/main/resources/application.yml
  server:
    waitTimeInMsWhenSyncEmpty: 0
    response-cache-update-interval-ms: 5000
management.endpoints.web.exposure.include: "*"

resilience4j.circuitbreaker:
  instances:
    product:
      allowHealthIndicatorToFail: false
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      ignoreExceptions:
        - se.chau.microservices.api.exception.InvalidInputException
        - se.chau.microservices.api.exception.NotFoundException
management.zipkin.tracing.endpoint: http://zipkin-server:9411/api/v2/spans
management.tracing.sampling.probability: 1.0
