spring.config.import: "optional:configserver:"
server:
  port: 8000


springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: se.magnus.microservices.composite.product
  pathsToMatch: /**
  cache.disabled: true

  swagger-ui:
    oauth2-redirect-url: /swagger-ui/oauth2-redirect.html
    oauth:
      clientId: writer
      clientSecret: secret-writer
      useBasicAuthenticationWithAccessCodeGrant: true
  oAuthFlow:
    authorizationUrl: https://localhost:8443/oauth2/authorize
    tokenUrl: https://localhost:8443/oauth2/token
spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application.name: product-composite

  config:
    failFast: true
    retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 10000
        maxAttempts: 20
    uri: http://localhost:8888
    username: user
    password: 123
api:
  common:
    apiVersion: 0.0.1
    appTitle: test choi cho vui
    appDescription: | # Normal response
      If the requested product id is found the method will return information regarding:
      1. Base product information
      1. Reviews
      1. Recommendations
      1. Service Addresses\n(technical information regarding the addresses of the microservices that created the response)
      
      # Expected partial and error responses
      In the following cases, only a partial response be created (used to simplify testing of error conditions)
      
      ## Product id 113
      200 - Ok, but no recommendations will be returned
      
      ## Product id 213
      200 - Ok, but no reviews will be returned
      
      ## Non numerical product id
      400 - A **Bad Request** error will be returned
      
      ## Product id 13
      404 - A **Not Found** error will be returned
      
      ## Negative product ids
      422 - An **Unprocessable Entity** error will be returned
    apiContactName: phamchau
    appContactUrl:  test phase
    appContactEmail: phamchaugiatu@gmail.com
    apiTermOfService: 12312
    appLicense: 12312
    apiLicenseUrl: 23123
    apiExternalDoc: 123123
    apiExternalUrl: 123122

server.port: 8000
server.error.include-message: always
spring.application.name: product-composite

app.eureka-server: localhost
logging:
  level:
    root: INFO
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    products-out-0:
      destination: products
      producer:
        required-groups: auditGroup
    recommendations-out-0:
      destination: recommendations
      producer:
        required-groups: auditGroup
    reviews-out-0:
      destination: reviews
      producer:
        required-groups: auditGroup
    features-out-0:
      destination: features
      producer:
        required-groups: auditGroup
spring.cloud.stream.bindings.products-out-0.producer:
  partition-key-expression: headers['partitionKey']
  partition-count: 2
spring.cloud.stream.bindings.recommendations-out-0.producer:
  partition-key-expression: headers['partitionKey']
  partition-count: 2
spring.cloud.stream.bindings.reviews-out-0.producer:
  partition-key-expression: headers['partitionKey']
  partition-count: 2
spring.cloud.stream.bindings.features-out-0.producer:
  partition-key-expression: headers['partitionKey']
  partition-count: 2
spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

resilience4j.timelimiter:
  instances:
    product:
      timeoutDuration: 2s

resilience4j.retry:
  instances:
    product:
      maxAttempts: 3
      waitDuration: 1000
      retryExceptions:
        - org.springframework.web.reactive.function.client.WebClientResponseException$InternalServerError

management.health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
  instances:
    product:
      allowHealthIndicatorToFail: false
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      ignoreExceptions:
        - se.chau.microservices.api.exception.InvalidInputException
        - se.chau.microservices.api.exception.NotFoundException
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:9999
management.zipkin.tracing.endpoint: http://zipkin-server:9411/api/v2/spans
management.tracing.sampling.probability: 1.0
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
---
spring.config.activate.on-profile: docker
server.port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: "http://eureka:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://auth-server:9999
spring.rabbitmq.host: rabbitmq
spring.cloud.stream.kafka.binder.brokers: kafka

---
spring.config.activate.on-profile: streaming_partitioned

spring.cloud.stream.bindings.products-out-0.producer:
  partition-key-expression: headers['partitionKey']
  partition-count: 2

spring.cloud.stream.bindings.recommendations-out-0.producer:
  partition-key-expression: headers['partitionKey']
  partition-count: 2

spring.cloud.stream.bindings.reviews-out-0.producer:
  partition-key-expression: headers['partitionKey']
  partition-count: 2
spring.cloud.stream.bindings.features-out-0.producer:
  partition-key-expression: headers['partitionKey']
  partition-count: 2