server.port: 8888

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: file:../../config-repo/  # Correct relative path to config-repo folder
  profiles:
    active: native  # Set the active profile to 'native' for file-based configuration

spring.cloud.compatibility-verifier.enabled: false

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"

# Docker-specific settings
---
spring.config.activate.on-profile: docker
spring.cloud.config.server.native.searchLocations: file:/config-repo  # If you use Docker, change this path to the Docker-mounted path
