spring.config.import: "configserver:"
spring.cloud.config.enabled: true
spring:
  application.name: message-server
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://config-server:8888
    username: ${CONFIG_SERVER_USR}
    password: ${CONFIG_SERVER_PWD} # Password for authentication
url-order: https://localhost:8443/order/user/
---
spring.config.activate.on-profile: docker
spring.cloud.config.uri: http://config-server:8888