# values.yaml

rabbitmq:
  username: "{{ .Env.RABBITMQ_USERNAME }}"  # Inject username from environment variable
  password: "{{ .Env.RABBITMQ_PASSWORD }}"  # Inject password from environment variable

# Default values for RabbitMQ chart (you can customize these too if needed)
replicaCount: 1
image:
  repository: "bitnami/rabbitmq"
  tag: "3.8.16"
  pullPolicy: "IfNotPresent"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500Mi"

service:
  type: ClusterIP
  port: 5672
  managementPort: 15672
