spring.mail.username: phamchaugiatu123@gmail.com
spring.mail.properties.mail.smtp.starttls.required: true
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.password: pdyw cdmz npfw qsmt
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.transport.protocol: smtp
spring.mail.properties.mail.smtp.starttls.enable: true